### ISSUE TITLE
Java Language

### ISSUE THREAD

**Issue by guoyoujin** [Yalantis/Multi-Selection#1]
The library is great, if I could use a `Java` implementation again

**Comment by defHLT** [comment]
Not sure what you mean. You can use this library from Java (as in sample)

**Comment by guoyoujin** [comment]
Yes, I do not understand `Kotlin`，You can convert `java`

**Comment by root1991** [comment]
No, we will not convert this library to java. Kotlin is new powerful and safe language, also it is easy to learn. You can read more about kotlin here: https://kotlinlang.org
Good luck

**Comment by guoyoujin** [comment]
Ok，Thank you
